yelpchi:
  train_ratio: 0.4
  lr: 0.01
  layer_num: 2
  hid_dim: 8
  head_num: 8
  dropMessage: 0.15
  eps: 0.1
  weight_decay: 5.0e-5
  homo: 0
  epochs: 500
  cuda: 0
  run: 1
  seed: 925

amazon:
  train_ratio: 0.4
  lr: 0.01
  layer_num: 1
  hid_dim: 64
  head_num: 1
  dropMessage: 0.00
  eps: 0.1
  weight_decay: 5.0e-5
  homo: 0
  epochs: 500
  cuda: 0
  run: 1
  seed: 925
